#!/usr/bin/env python3
"""Generate Raido rune icon assets from geometry primitives.

Source of truth is `icons/raido-base.svg`; this script renders the same
geometry via PIL so we don't need a headless SVG renderer in CI. Output:
  - PNGs at 16, 32, 64, 128, 256, 512, 1024 (transparent background, rust)
  - ICO bundle (16/32/48/64/128/256) for Windows tray + bundler
  - Status-colour variants (green/yellow/red/gray) at 16/32 — the whole
    rune is recoloured (governor-polish BOM Cluster A, concept 6 bare
    glyph). No tile, no halo, no circle — status is the colour of the
    glyph itself.

Run from repo root:  python governor/scripts/gen_icons.py
"""
from __future__ import annotations

from pathlib import Path
from PIL import Image, ImageDraw

ICONS = Path(__file__).resolve().parent.parent / "icons"
SIZES = [16, 32, 64, 128, 256, 512, 1024]
ICO_SIZES = [16, 32, 48, 64, 128, 256]

# Iron palette — match the dashboard tokens. Brand stays rust; the four
# status colours recolour the entire glyph (concept 6, no halo).
RUST_ORANGE = (250, 156, 76, 255)   # #fa9c4c — Brand / idle
GREEN       = (95, 217, 135, 255)   # #5fd987 — Healthy
YELLOW      = (255, 217, 90, 255)   # #ffd95a — Degraded
RED         = (255, 122, 122, 255)  # #ff7a7a — Down / GiveUp
GRAY        = (138, 138, 138, 255)  # #8a8a8a — StoppedManually

# Geometry expressed on a 100-unit grid (matches design-mockups/dock-icon-mockups.html `#rune`).
BASE = 100.0
STROKE_BASE = 11.0  # at 100x100


def _scale(p: tuple[float, float], size: int) -> tuple[float, float]:
    s = size / BASE
    return (p[0] * s, p[1] * s)


def _stroke_width(size: int) -> int:
    # Keep stroke proportional but readable at tray sizes.
    w = max(2.0, STROKE_BASE * (size / BASE))
    return int(round(w))


def _draw_rune(size: int, color: tuple[int, int, int, int]) -> Image.Image:
    """Render the concept-6 bare rune at `size` px in `color`.

    Geometry mirrors the dock-icon-mockup SVG: staff (38,20)→(38,80);
    bow (38,20)→(68,33)→(38,50); leg (38,50)→(68,80). Round caps/joins
    are stamped manually because PIL's `Image.Draw.line` doesn't expose
    a stroke-linejoin parameter.
    """
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    sw = _stroke_width(size)

    # Geometry points in 100-grid space.
    staff_top = (38, 20)
    staff_mid = (38, 50)
    staff_bot = (38, 80)
    bow_tip   = (68, 33)
    leg_end   = (68, 80)

    p_staff_top = _scale(staff_top, size)
    p_staff_mid = _scale(staff_mid, size)
    p_staff_bot = _scale(staff_bot, size)
    p_bow_tip   = _scale(bow_tip,   size)
    p_leg_end   = _scale(leg_end,   size)

    # Vertical staff
    draw.line([p_staff_top, p_staff_bot], fill=color, width=sw)
    # Upper bow (two segments meeting at bow_tip)
    draw.line([p_staff_top, p_bow_tip], fill=color, width=sw)
    draw.line([p_bow_tip, p_staff_mid], fill=color, width=sw)
    # Lower leg
    draw.line([p_staff_mid, p_leg_end], fill=color, width=sw)

    # Round joints by stamping circles at every vertex.
    r = max(1, sw // 2)
    for vx, vy in (p_staff_top, p_staff_mid, p_staff_bot, p_bow_tip, p_leg_end):
        draw.ellipse(
            [(vx - r, vy - r), (vx + r, vy + r)],
            fill=color,
        )
    return img


def main() -> int:
    ICONS.mkdir(parents=True, exist_ok=True)

    # Base brand glyph (rust orange) at all sizes — bundle icon, About
    # dialog, pre-launch tray placeholder.
    for s in SIZES:
        out = ICONS / f"raido-{s}.png"
        _draw_rune(s, RUST_ORANGE).save(out, "PNG")
        print(f"wrote {out.relative_to(ICONS.parent)} ({s}x{s})")

    # ICO bundle for Windows tray + bundler.
    ico_layers = [_draw_rune(s, RUST_ORANGE) for s in ICO_SIZES]
    ico_path = ICONS / "raido-icon.ico"
    ico_layers[0].save(
        ico_path,
        format="ICO",
        sizes=[(s, s) for s in ICO_SIZES],
        append_images=ico_layers[1:],
    )
    print(f"wrote {ico_path.relative_to(ICONS.parent)} (ICO, {ICO_SIZES})")

    # Status-colour variants — the whole rune recoloured (concept 6, no
    # halo). Tray uses 16/32 directly via `IconVariant::bytes_{16,32}`.
    variants = {
        "green":  GREEN,
        "yellow": YELLOW,
        "red":    RED,
        "gray":   GRAY,
    }
    for name, color in variants.items():
        for s in (16, 32):
            out = ICONS / f"raido-{name}-{s}.png"
            _draw_rune(s, color).save(out, "PNG")
            print(f"wrote {out.relative_to(ICONS.parent)} ({name} {s}x{s})")

    # macOS .icns is generated by `cargo tauri icon` during bundling from
    # raido-1024.png; Pillow's ICNS writer is patchy across versions.

    print("OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
