#!/usr/bin/env python3
"""Generate Raido rune icon assets from geometry primitives.

Source of truth is `icons/raido-base.svg`; this script renders the same
geometry via PIL so we don't need a headless SVG renderer in CI. Output:
  - PNGs at 16, 32, 64, 128, 256, 512, 1024 (transparent background)
  - ICO bundle (16/32/48/64/128/256) for Windows tray + bundler
  - Halo color variants for state-driven swapping (green/yellow/red/gray/orange)

Run from repo root:  python governor/scripts/gen_icons.py
"""
from __future__ import annotations

from pathlib import Path
from PIL import Image, ImageDraw

ICONS = Path(__file__).resolve().parent.parent / "icons"
SIZES = [16, 32, 64, 128, 256, 512, 1024]
ICO_SIZES = [16, 32, 48, 64, 128, 256]

# Iron palette
RUST_ORANGE = (250, 156, 76, 255)   # #fa9c4c — default brand
GREEN       = (95, 217, 135, 255)   # #5fd987 — Healthy
YELLOW      = (255, 217, 90, 255)   # #ffd95a — Degraded
RED         = (255, 122, 122, 255)  # #ff7a7a — Down / GiveUp
GRAY        = (138, 138, 138, 255)  # #8a8a8a — StoppedManually
PULSE_DIM   = (250, 156, 76, 110)   # rust orange, low-alpha — Restarting frame 2

# Geometry expressed at 128x128, scaled per output size.
BASE = 128.0
STROKE_BASE = 14.0  # at 128x128


def _scale(p: tuple[float, float], size: int) -> tuple[float, float]:
    s = size / BASE
    return (p[0] * s, p[1] * s)


def _stroke_width(size: int) -> int:
    # keep stroke proportional but readable at small sizes
    w = max(2.0, STROKE_BASE * (size / BASE))
    return int(round(w))


def _draw_rune(size: int, color: tuple[int, int, int, int]) -> Image.Image:
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    sw = _stroke_width(size)

    # vertical staff
    p1 = _scale((34, 20), size)
    p2 = _scale((34, 108), size)
    draw.line([p1, p2], fill=color, width=sw)

    # upper bow: staff-top → mid-right → staff-middle
    bow = [
        _scale((34, 20), size),
        _scale((90, 38), size),
        _scale((34, 62), size),
    ]
    draw.line([bow[0], bow[1]], fill=color, width=sw)
    draw.line([bow[1], bow[2]], fill=color, width=sw)

    # lower leg: staff-middle → bottom-right
    p3 = _scale((34, 62), size)
    p4 = _scale((92, 108), size)
    draw.line([p3, p4], fill=color, width=sw)

    # round joints by stamping circles at the vertices
    r = max(1, sw // 2)
    for vx, vy in [p1, p2, bow[0], bow[1], bow[2], p3, p4]:
        draw.ellipse(
            [(vx - r, vy - r), (vx + r, vy + r)],
            fill=color,
        )
    return img


def _draw_halo_variant(size: int, halo: tuple[int, int, int, int]) -> Image.Image:
    """Rune in rust orange surrounded by a translucent halo ring of the state color.

    P3 hard rule: status = halo ring; type = node color. The base glyph stays rust
    orange (the brand) — the halo conveys state. For 16/32 px tray icons we still
    use a single-color glyph because halo detail is invisible at that size; only
    32+ gets the halo.
    """
    img = _draw_rune(size, RUST_ORANGE)
    if size >= 32:
        ring = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        rd = ImageDraw.Draw(ring)
        margin = max(1, size // 16)
        ring_w = max(2, size // 16)
        rd.ellipse(
            [(margin, margin), (size - margin, size - margin)],
            outline=halo,
            width=ring_w,
        )
        img = Image.alpha_composite(ring, img)
    else:
        # at 16 px, tint the whole glyph to the halo color so state still reads
        img = _draw_rune(size, halo)
    return img


def main() -> int:
    ICONS.mkdir(parents=True, exist_ok=True)

    # Base brand icon (rust orange) at all sizes
    for s in SIZES:
        out = ICONS / f"raido-{s}.png"
        _draw_rune(s, RUST_ORANGE).save(out, "PNG")
        print(f"wrote {out.relative_to(ICONS.parent)} ({s}x{s})")

    # ICO bundle for Windows tray + bundler
    ico_layers = [_draw_rune(s, RUST_ORANGE) for s in ICO_SIZES]
    ico_path = ICONS / "raido-icon.ico"
    ico_layers[0].save(
        ico_path,
        format="ICO",
        sizes=[(s, s) for s in ICO_SIZES],
        append_images=ico_layers[1:],
    )
    print(f"wrote {ico_path.relative_to(ICONS.parent)} (ICO, {ICO_SIZES})")

    # Halo color variants for state machine (P3). Each at 16 and 32.
    variants = {
        "green": GREEN,
        "yellow": YELLOW,
        "red": RED,
        "gray": GRAY,
        "orange": RUST_ORANGE,
        "orange-dim": PULSE_DIM,
    }
    for name, color in variants.items():
        for s in (16, 32):
            out = ICONS / f"raido-{name}-{s}.png"
            _draw_halo_variant(s, color).save(out, "PNG")
            print(f"wrote {out.relative_to(ICONS.parent)} ({name} {s}x{s})")

    # macOS .icns is generated by `cargo tauri icon` during bundling from
    # raido-1024.png; we skip the PIL ICNS path because Pillow's ICNS writer
    # is patchy across versions. The 1024 PNG above is the seed.

    print("OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
