/**
 * Generate docs/tool-catalogue.json + docs/tool-cards/*.md from
 * src/tools/catalogue-data.ts. Single source of truth: that file.
 *
 * Sync invariant: `npm run docs:tools` must produce no git diff. CI enforces it
 * via tests/tool-catalogue.test.ts (which asserts the catalogue parses + every
 * registered tool name appears in TOOL_DEFINITIONS).
 */
import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { zodToJsonSchema } from 'zod-to-json-schema';
import {
  TOOL_DEFINITIONS,
  type ToolDefinition,
} from '../src/tools/catalogue-data.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const DOCS = join(ROOT, 'docs');
const CARDS_DIR = join(DOCS, 'tool-cards');
const CATALOGUE_PATH = join(DOCS, 'tool-catalogue.json');

function sanitizeFileName(name: string): string {
  // 'github.read_pr' → 'github_read_pr.md'
  return name.replace(/\./g, '_') + '.md';
}

function toJsonSchema(schema: ToolDefinition['inputSchema']): unknown {
  // `target: 'jsonSchema7'` produces drafts most viewers handle. We omit the
  // `$schema` field on outputs to keep diffs small — the docs themselves note
  // the version.
  const result = zodToJsonSchema(schema, { target: 'jsonSchema7', $refStrategy: 'none' });
  // zod-to-json-schema adds `$schema` by default — strip for stable output.
  if (result && typeof result === 'object' && '$schema' in result) {
    const copy: Record<string, unknown> = { ...(result as Record<string, unknown>) };
    delete copy.$schema;
    return copy;
  }
  return result;
}

function renderCard(def: ToolDefinition, inputSchema: unknown, outputSchema: unknown): string {
  const tierBehaviour = describeTier(def.tier);
  const sideEffects = def.sideEffects.length
    ? def.sideEffects.map((s) => `- ${s}`).join('\n')
    : '- _(none documented)_';
  const errorModes = def.errorModes.length
    ? def.errorModes.map((s) => `- ${s}`).join('\n')
    : '- _(none documented)_';
  const seeAlso = def.seeAlso.length
    ? def.seeAlso.map((s) => `- \`${s}\``).join('\n')
    : '- _(none)_';

  let exampleBlock = '';
  if (def.example) {
    exampleBlock = `

## Example

\`\`\`json
${JSON.stringify({ args: def.example.args, result: def.example.result }, null, 2)}
\`\`\``;
  }

  return `---
name: ${def.name}
tier: ${def.tier}
category: ${def.category}
since: ${def.since}
stability: ${def.stability}
---

# ${def.name}

${def.description}

## Tier behaviour

${tierBehaviour}

## Input schema

\`\`\`json
${JSON.stringify(inputSchema, null, 2)}
\`\`\`

## Output schema

\`\`\`json
${JSON.stringify(outputSchema, null, 2)}
\`\`\`

## Side effects

${sideEffects}
${exampleBlock}

## Error modes

${errorModes}

## See also

${seeAlso}

---

_This file is generated by \`scripts/generate-tool-catalogue.ts\`. Edit \`src/tools/catalogue-data.ts\` and re-run \`npm run docs:tools\`._
`;
}

function describeTier(tier: ToolDefinition['tier']): string {
  switch (tier) {
    case 'auto':
      return 'AUTO — runs without confirmation. Read-only or has built-in escape hatches; the caller is responsible for using it intentionally.';
    case 'confirm':
      return 'CONFIRM — opens an `await_decision` first. Only proceeds on approve. On reject/timeout, returns `{ ok: false, reason: ... }` and emits no success event. Trust scopes may grant blanket pre-approval for matching invocations (see [`docs/tool-cards/trust_scope_grant.md`](./trust_scope_grant.md)).';
    case 'never':
      return 'NEVER — destructive operations that stay manual; not exposed through this tool surface. See [ADR-018](../../adr/018-destructive-operations-stay-manual.md).';
    case 'per-spawner':
      return 'PER-SPAWNER — the tier comes from the spawner registration. Default for built-in spawners (`cc`, `shell`) is CONFIRM.';
  }
}

function main(): void {
  mkdirSync(DOCS, { recursive: true });
  // Wipe existing cards so removed tools don't linger. The directory only
  // contains generated files; nothing hand-edited lives here.
  try {
    const existing = readdirSync(CARDS_DIR);
    for (const f of existing) {
      if (f.endsWith('.md')) rmSync(join(CARDS_DIR, f));
    }
  } catch {
    // Directory may not exist yet.
  }
  mkdirSync(CARDS_DIR, { recursive: true });

  const seen = new Set<string>();
  const cataloguEntries: Array<{
    name: string;
    tier: string;
    category: string;
    since: string;
    stability: string;
    description: string;
    input_schema: unknown;
    output_schema: unknown;
    side_effects: string[];
    error_modes: string[];
    see_also: string[];
    card_path: string;
    example?: { args: unknown; result: unknown };
  }> = [];

  // Sort for stable output regardless of source order.
  const sorted = [...TOOL_DEFINITIONS].sort((a, b) => a.name.localeCompare(b.name));

  for (const def of sorted) {
    if (seen.has(def.name)) {
      throw new Error(`duplicate tool name in TOOL_DEFINITIONS: ${def.name}`);
    }
    seen.add(def.name);
    const inputSchema = toJsonSchema(def.inputSchema);
    const outputSchema = toJsonSchema(def.outputSchema);
    const cardFileName = sanitizeFileName(def.name);
    writeFileSync(join(CARDS_DIR, cardFileName), renderCard(def, inputSchema, outputSchema));
    cataloguEntries.push({
      name: def.name,
      tier: def.tier,
      category: def.category,
      since: def.since,
      stability: def.stability,
      description: def.description,
      input_schema: inputSchema,
      output_schema: outputSchema,
      side_effects: def.sideEffects,
      error_modes: def.errorModes,
      see_also: def.seeAlso,
      card_path: `docs/tool-cards/${cardFileName}`,
      example: def.example,
    });
  }

  // generated_at deliberately omitted from the JSON to keep `npm run docs:tools`
  // diff-free. The spec example shows it, but a reproducibility-friendly
  // catalogue must not embed wall-clock state — we put it in a sidecar field
  // instead, sourced from the git commit that produced the file (handled by
  // CI/release tooling, not this script). For now: a stable placeholder.
  const catalogue = {
    schema_version: 1,
    generated_at: 'reproducible-build',
    note: 'Generated by scripts/generate-tool-catalogue.ts. Do not hand-edit; edit src/tools/catalogue-data.ts and re-run `npm run docs:tools`.',
    tools: cataloguEntries,
  };

  writeFileSync(CATALOGUE_PATH, JSON.stringify(catalogue, null, 2) + '\n');

  console.log(
    `Wrote ${cataloguEntries.length} tool cards → ${CARDS_DIR}\nWrote catalogue → ${CATALOGUE_PATH}`,
  );
}

main();
